import Head from "next/head";
import Create_Page from "../components/Create/Create_Page";
const Create = () => {
  return (
    <>
      <Head>
        <title>Create Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Create_Page />
    </>
  );
};

export default Create;
