import Head from "next/head";
import HomePage from "../components/Home/Home";
import { itemHot, topList, discoverMore } from "../components/Home/homeArray";
const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage
        itemHot={itemHot}
        topList={topList}
        discoverMore={discoverMore}
      />
    </>
  );
};

export default Home;
