import Head from "next/head";
import Item_Page from "../components/Item/Item_Page";
const Item = () => {
  return (
    <>
      <Head>
        <title>Item Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Item_Page />
    </>
  );
};

export default Item;
