import Head from "next/head";
import Privacy_Policy_Page from "../components/Privacy-Policy/PrivacyPolicy";
const Item = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Privacy_Policy_Page />
    </>
  );
};

export default Item;
